[package]
name = "radiobrowser-api-rust"
version = "0.1.0"
authors = ["segler_alex"]
license = "agpl-3.0"
description = "Radio-Browser Server with REST API"
readme = "README.md"

[dependencies]
av-stream-info-rust = "0.5.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "*"
colored = "1.8.0"
dns-lookup = "*"
env_logger = "*"
handlebars = "*"
hostname = "0.1.5"
log = "*"
mysql = "16.0.2"
native-tls = "0.2.3"
reqwest = "*"
rouille = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
#slog = "*"
#slog-async = "*"
#slog-scope = "*"
#slog-stdlog = "*"
#slog-term = "*"
threadpool = "1.7.1"
toml = "*"
url = "1.7.2"
uuid = { version = "*", features = ["serde", "v4"] }
website-icon-extract = "0.4.0"
xml_writer = "*"

[package.metadata.deb]
maintainer = "sailor <segler@programmierecke.net>"
copyright = "2018, sailor <segler@programmierecke.net>"
depends = "$auto, systemd"
extended-description = """\
Radio-Browser Server with REST API
"""
section = "admin"
priority = "optional"
assets = [
    ["target/release/radiobrowser-api-rust", "usr/local/bin/radiobrowser", "755"],
    ["static/*", "usr/local/share/radiobrowser/", "644"],
    ["init/*", "etc/sytemd/system/", "644"],
    ["radiobrowser.toml", "etc/", "644"],
]
conf-files = [
    "radiobrowser.toml",
]
maintainer-scripts = "debian/"