[package]
authors = ["segler_alex"]
description = "Radio-Browser Server with REST API"
license = "agpl-3.0"
name = "radiobrowser-api-rust"
readme = "README.md"
version = "0.1.0"
edition = "2018"

[dependencies]
av-stream-info-rust = "0.6.1"
chrono = { version = "0.4.9", features = ["serde"] }
clap = "2.33.0"
colored = "1.8.0"
dns-lookup = "1.0.1"
env_logger = "0.7.0"
handlebars = "2.0.2"
hostname = "0.1.5"
log = "0.4.8"
mysql = "16.1.0"
native-tls = "0.2.3"
reqwest = "0.9.21"
rouille = "3.0.0"
serde = "1.0.101"
serde_derive ="1.0.101"
serde_json = "1.0.41"
threadpool = "1.7.1"
toml = "0.5.3"
url = "2.1.0"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
website-icon-extract = "0.4.1"
xml_writer = "0.4.0"

[package.metadata.deb]
maintainer = "sailor <segler@programmierecke.net>"
copyright = "2018, sailor <segler@programmierecke.net>"
depends = "$auto, systemd"
extended-description = """\
Radio-Browser Server with REST API
"""
section = "admin"
priority = "optional"
assets = [
    ["target/release/radiobrowser-api-rust", "usr/local/bin/radiobrowser", "755"],
    ["static/*", "usr/local/share/radiobrowser/", "644"],
    ["init/*", "etc/sytemd/system/", "644"],
    ["radiobrowser.toml", "etc/", "644"],
]
conf-files = [
    "radiobrowser.toml",
]
maintainer-scripts = "debian/"