[package]
name = "radiobrowser-api-rust"
version = "0.1.0"
authors = ["segler_alex"]

[dependencies]
rouille = "*"
clap = "*"
mysql = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
dns-lookup = "*"
xml_writer = "*"
chrono = { version = "0.4", features = ["serde"] }
handlebars = "*"
url = "*"
uuid = { version = "*", features = ["serde", "v4"] }
reqwest = "*"