version: "3.0"
services:
  api:
    image: segleralex/radiobrowser-api-rust:latest
    deploy:
      replicas: 1
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
       - DB_USER=radiouser
       - DB_PASS=password
       - DB_HOST=dbserver
       - DB_NAME=radio
       - HOST=0.0.0.0
  dbserver:
    image: mariadb:latest
    deploy:
      replicas: 1
    environment:
       - MYSQL_ROOT_PASSWORD=12345678
       - MYSQL_USER=radiouser
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=radio
    networks:
      - mynet
    volumes:
      - ./radio.sql.gz:/docker-entrypoint-initdb.d/radio.sql.gz
      - ./dbdata:/var/lib/mysql
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
networks:
  mynet:
    driver: "overlay"
    driver_opts:
      encrypted: ""
